Repository TeamOrderLink/OrderLink-Server, pull requests merged in 2025-02, with the labels that each got.

#3 [Feat] 주문 기능 생성
  src/main/java/com/order/orderlink/OrderLinkApplication.java
  src/main/java/com/order/orderlink/common/auth/filter/JwtAuthorizationFilter.java
  src/main/java/com/order/orderlink/common/client/RestaurantClient.java
  src/main/java/com/order/orderlink/common/client/UserClient.java
  src/main/java/com/order/orderlink/common/config/AuditConfig.java
  src/main/java/com/order/orderlink/common/config/AuditorAwareImpl.java
  src/main/java/com/order/orderlink/common/dtos/ErrorNonDataResponse.java
  src/main/java/com/order/orderlink/common/dtos/ErrorResponse.java
  src/main/java/com/order/orderlink/common/dtos/SuccessNonDataResponse.java
  src/main/java/com/order/orderlink/common/dtos/SuccessResponse.java
  src/main/java/com/order/orderlink/common/entity/BaseTimeEntity.java
  src/main/java/com/order/orderlink/common/enums/ErrorCode.java
  src/main/java/com/order/orderlink/common/enums/SuccessCode.java
  src/main/java/com/order/orderlink/common/exception/AuthException.java
  src/main/java/com/order/orderlink/common/exception/GlobalExceptionHandler.java
  src/main/java/com/order/orderlink/order/application/OrderService.java
  src/main/java/com/order/orderlink/order/application/dtos/OrderFoodDTO.java
  src/main/java/com/order/orderlink/order/application/dtos/OrderRequest.java
  src/main/java/com/order/orderlink/order/application/dtos/OrderResponse.java
  src/main/java/com/order/orderlink/order/domain/Order.java
  src/main/java/com/order/orderlink/order/domain/OrderStatus.java
  src/main/java/com/order/orderlink/order/domain/OrderType.java
  src/main/java/com/order/orderlink/order/domain/repository/OrderRepository.java
  src/main/java/com/order/orderlink/order/presentation/OrderController.java
  src/main/java/com/order/orderlink/orderitem/application/OrderItemService.java
  src/main/java/com/order/orderlink/orderitem/domain/OrderItem.java
  src/main/java/com/order/orderlink/orderitem/domain/repository/OrderItemRepository.java
  src/main/java/com/order/orderlink/orderitem/presentation/OrderController.java
  src/main/java/com/order/orderlink/user/application/dtos/LoginRequestDto.java
Labels: feat

#4 [Fix] Auditor 사용시에 인증 객체가 없을 경우(회원가입시 등)에 String 타입으로 주체를 반환하도록 변경
  src/main/java/com/order/orderlink/common/config/AuditorAwareImpl.java
  src/main/java/com/order/orderlink/user/domain/UserRoleEnum.java
  src/main/java/com/order/orderlink/user/domain/repository/UserRepository.java
Labels: fix

#5 [Feat] 내 주문 목록 조회 api 추가
  src/main/java/com/order/orderlink/common/enums/ErrorCode.java
  src/main/java/com/order/orderlink/common/enums/SuccessCode.java
  src/main/java/com/order/orderlink/common/exception/OrderException.java
  src/main/java/com/order/orderlink/common/exception/RestaurantException.java
  src/main/java/com/order/orderlink/order/application/OrderService.java
  src/main/java/com/order/orderlink/order/application/dtos/OrderDTO.java
  src/main/java/com/order/orderlink/order/application/dtos/OrderFoodDTO.java
  src/main/java/com/order/orderlink/order/application/dtos/OrderRequest.java
  src/main/java/com/order/orderlink/order/application/dtos/OrderResponse.java
  src/main/java/com/order/orderlink/order/domain/repository/OrderRepository.java
  src/main/java/com/order/orderlink/order/presentation/OrderController.java
  src/main/java/com/order/orderlink/restaurant/domain/Restaurant.java
  src/main/java/com/order/orderlink/restaurant/domain/repository/RestaurantRepository.java
Labels: feat

#6 [Feat] 회원가입 & 로그인 기능 추가
  src/main/java/com/order/orderlink/common/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/order/orderlink/common/auth/util/JwtUtil.java
  src/main/java/com/order/orderlink/common/dtos/ApiResponse.java
  src/main/java/com/order/orderlink/common/dtos/AuthRequest.java
  src/main/java/com/order/orderlink/common/dtos/AuthResponse.java
  src/main/java/com/order/orderlink/common/dtos/OrderRequest.java
  src/main/java/com/order/orderlink/common/dtos/OrderResponse.java
  src/main/java/com/order/orderlink/common/enums/SuccessCode.java
  src/main/java/com/order/orderlink/common/exception/RestApiException.java
  src/main/java/com/order/orderlink/user/application/UserService.java
  src/main/java/com/order/orderlink/user/application/dtos/LoginRequestDto.java
  src/main/java/com/order/orderlink/user/application/dtos/UserRequest.java
  src/main/java/com/order/orderlink/user/application/dtos/UserResponse.java
  src/main/java/com/order/orderlink/user/domain/User.java
  src/main/java/com/order/orderlink/user/presentation/UserController.java
Labels: feat

#7 [Feat] 주문 상세 조회 기능 추가
  src/main/java/com/order/orderlink/common/enums/SuccessCode.java
  src/main/java/com/order/orderlink/order/application/OrderService.java
  src/main/java/com/order/orderlink/order/application/dtos/OrderResponse.java
  src/main/java/com/order/orderlink/order/domain/Order.java
  src/main/java/com/order/orderlink/order/presentation/OrderController.java
  src/main/java/com/order/orderlink/payment/domain/Payment.java
  src/main/java/com/order/orderlink/payment/domain/PaymentStatus.java
Labels: feat

#8 [Feat] 내 정보 조회, 회원 정보 수정, 회원 삭제, 비밀번호 변경 추가
  src/main/java/com/order/orderlink/common/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/order/orderlink/common/enums/ErrorCode.java
  src/main/java/com/order/orderlink/common/enums/SuccessCode.java
  src/main/java/com/order/orderlink/common/exception/GlobalExceptionHandler.java
  src/main/java/com/order/orderlink/common/exception/UserException.java
  src/main/java/com/order/orderlink/user/application/UserService.java
  src/main/java/com/order/orderlink/user/application/dtos/UserRequest.java
  src/main/java/com/order/orderlink/user/application/dtos/UserResponse.java
  src/main/java/com/order/orderlink/user/domain/User.java
  src/main/java/com/order/orderlink/user/presentation/UserController.java
Labels: feat

#9 [Feat] 주문 상태 변경 api 기능 구현
  src/main/java/com/order/orderlink/common/enums/SuccessCode.java
  src/main/java/com/order/orderlink/order/application/OrderService.java
  src/main/java/com/order/orderlink/order/application/dtos/OrderRequest.java
  src/main/java/com/order/orderlink/order/application/dtos/OrderResponse.java
  src/main/java/com/order/orderlink/order/domain/Order.java
  src/main/java/com/order/orderlink/order/presentation/OrderController.java
Labels: feat

#13 [Feat] 음식 등록 기능 추가
  src/main/java/com/order/orderlink/common/enums/SuccessCode.java
  src/main/java/com/order/orderlink/food/application/FoodService.java
  src/main/java/com/order/orderlink/food/application/dtos/FoodCreateRequest.java
  src/main/java/com/order/orderlink/food/application/dtos/FoodRequest.java
  src/main/java/com/order/orderlink/food/application/dtos/FoodResponse.java
  src/main/java/com/order/orderlink/food/domain/Food.java
  src/main/java/com/order/orderlink/food/presentation/FoodController.java
Labels: feat

#11 [Feat] 주문 검색 기능 추가
  build.gradle
  src/main/java/com/order/orderlink/common/config/QueryDslConfig.java
  src/main/java/com/order/orderlink/common/enums/SuccessCode.java
  src/main/java/com/order/orderlink/order/application/OrderService.java
  src/main/java/com/order/orderlink/order/application/dtos/OrderRequest.java
  src/main/java/com/order/orderlink/order/domain/repository/OrderRepository.java
  src/main/java/com/order/orderlink/order/domain/repository/OrderRepositoryCustom.java
  src/main/java/com/order/orderlink/order/domain/repository/OrderRepositoryImpl.java
  src/main/java/com/order/orderlink/order/domain/repository/OrderSearchRepository.java
  src/main/java/com/order/orderlink/order/infrastructure/OrderSearchRepositoryImpl.java
  src/main/java/com/order/orderlink/order/presentation/OrderController.java
Labels: feat

#14 [Feat] 결제내역 생성 추가
  src/main/java/com/order/orderlink/common/client/OrderClient.java
  src/main/java/com/order/orderlink/common/enums/SuccessCode.java
  src/main/java/com/order/orderlink/order/application/OrderService.java
  src/main/java/com/order/orderlink/order/domain/Order.java
  src/main/java/com/order/orderlink/order/presentation/OrderController.java
  src/main/java/com/order/orderlink/payment/application/PaymentService.java
  src/main/java/com/order/orderlink/payment/application/dtos/PaymentRequest.java
  src/main/java/com/order/orderlink/payment/application/dtos/PaymentResponse.java
  src/main/java/com/order/orderlink/payment/domain/repository/JpaPaymentRepository.java
  src/main/java/com/order/orderlink/payment/presentation/PaymentController.java
Labels: feat

#15 [Feat] 관리자 권한으로 회원 조회 및 수정 기능
  src/main/java/com/order/orderlink/common/config/SecurityConfig.java
  src/main/java/com/order/orderlink/common/enums/SuccessCode.java
  src/main/java/com/order/orderlink/common/exception/GlobalExceptionHandler.java
  src/main/java/com/order/orderlink/user/application/UserService.java
  src/main/java/com/order/orderlink/user/application/dtos/UserRequest.java
  src/main/java/com/order/orderlink/user/application/dtos/UserResponse.java
  src/main/java/com/order/orderlink/user/domain/User.java
  src/main/java/com/order/orderlink/user/presentation/UserController.java
Labels: feat

#16 [Feat] 결제 내역 상세 조회 api
  src/main/java/com/order/orderlink/common/client/UserClient.java
  src/main/java/com/order/orderlink/common/enums/ErrorCode.java
  src/main/java/com/order/orderlink/common/enums/SuccessCode.java
  src/main/java/com/order/orderlink/common/exception/PaymentException.java
  src/main/java/com/order/orderlink/order/application/OrderService.java
  src/main/java/com/order/orderlink/order/application/dtos/OrderDTO.java
  src/main/java/com/order/orderlink/order/application/dtos/RestaurantOrderDTO.java
  src/main/java/com/order/orderlink/order/domain/repository/OrderRepositoryImpl.java
  src/main/java/com/order/orderlink/order/presentation/OrderController.java
  src/main/java/com/order/orderlink/payment/application/PaymentService.java
  src/main/java/com/order/orderlink/payment/application/dtos/PaymentResponse.java
  src/main/java/com/order/orderlink/payment/domain/repository/JpaPaymentRepository.java
  src/main/java/com/order/orderlink/payment/presentation/PaymentController.java
  src/main/java/com/order/orderlink/user/presentation/UserController.java
Labels: feat

#17 [Feat] 배송 상세 CRUD API 추가
  src/main/java/com/order/orderlink/common/enums/ErrorCode.java
  src/main/java/com/order/orderlink/common/enums/SuccessCode.java
  src/main/java/com/order/orderlink/common/exception/DeliveryDetailException.java
  src/main/java/com/order/orderlink/deliverydetail/application/dtos/DeliveryDetailRequest.java
  src/main/java/com/order/orderlink/deliverydetail/application/dtos/DeliveryDetailResponse.java
  src/main/java/com/order/orderlink/deliverydetail/application/dtos/DeliveryDetailService.java
  src/main/java/com/order/orderlink/deliverydetail/domain/DeliveryDetail.java
  src/main/java/com/order/orderlink/deliverydetail/domain/repository/DeliveryDetailRepository.java
  src/main/java/com/order/orderlink/deliverydetail/presentation/DeliveryDetailController.java
Labels: feat

#18 [Feat] 카테고리 추가, 음식점에 카테고리 등록, 카테고리 리스트 조회 기능 구현
  src/main/java/com/order/orderlink/category/application/CategoryService.java
  src/main/java/com/order/orderlink/category/application/dtos/CategoryDTO.java
  src/main/java/com/order/orderlink/category/application/dtos/CategoryRequest.java
  src/main/java/com/order/orderlink/category/application/dtos/CategoryResponse.java
  src/main/java/com/order/orderlink/category/domain/Category.java
  src/main/java/com/order/orderlink/category/domain/RestaurantCategory.java
  src/main/java/com/order/orderlink/category/domain/repository/JpaCategoryRepository.java
  src/main/java/com/order/orderlink/category/domain/repository/JpaRestaurantCategoryRepository.java
  src/main/java/com/order/orderlink/category/presentation/CategoryController.java
  src/main/java/com/order/orderlink/common/config/SecurityConfig.java
  src/main/java/com/order/orderlink/common/enums/ErrorCode.java
  src/main/java/com/order/orderlink/common/enums/SuccessCode.java
  src/main/java/com/order/orderlink/common/exception/CategoryException.java
Labels: feat

#19 [Feat] 카테고리 수정 및 삭제 기능 구현
  src/main/java/com/order/orderlink/category/application/CategoryService.java
  src/main/java/com/order/orderlink/category/application/dtos/CategoryRequest.java
  src/main/java/com/order/orderlink/category/domain/Category.java
  src/main/java/com/order/orderlink/category/domain/repository/JpaRestaurantCategoryRepository.java
  src/main/java/com/order/orderlink/category/presentation/CategoryController.java
  src/main/java/com/order/orderlink/common/enums/SuccessCode.java
Labels: feat

#20 [Feat] 음식 수정 기능 추가
  src/main/java/com/order/orderlink/common/enums/ErrorCode.java
  src/main/java/com/order/orderlink/common/enums/SuccessCode.java
  src/main/java/com/order/orderlink/common/exception/FoodException.java
  src/main/java/com/order/orderlink/food/application/FoodService.java
  src/main/java/com/order/orderlink/food/application/dtos/FoodRequest.java
  src/main/java/com/order/orderlink/food/application/dtos/FoodResponse.java
  src/main/java/com/order/orderlink/food/domain/Food.java
  src/main/java/com/order/orderlink/food/domain/repository/FoodRepository.java
  src/main/java/com/order/orderlink/food/presentation/FoodController.java
Labels: feat

#23 [Fix] 타인의 배송지에 대한 조회/수정/삭제 불가하도록 로직 개선, 동시에 여러 배송지가 기본 배송지로 등록될 수 있던 문제 수정
  src/main/java/com/order/orderlink/address/application/AddressService.java
  src/main/java/com/order/orderlink/address/application/dtos/AddressRequest.java
  src/main/java/com/order/orderlink/address/application/dtos/AddressResponse.java
  src/main/java/com/order/orderlink/address/domain/Address.java
  src/main/java/com/order/orderlink/address/domain/repository/AddressRepository.java
  src/main/java/com/order/orderlink/address/presentation/AddressController.java
  src/main/java/com/order/orderlink/common/auth/filter/JwtAuthorizationFilter.java
  src/main/java/com/order/orderlink/common/auth/util/JwtUtil.java
  src/main/java/com/order/orderlink/common/enums/ErrorCode.java
  src/main/java/com/order/orderlink/common/enums/SuccessCode.java
  src/main/java/com/order/orderlink/common/exception/AddressException.java
  src/main/java/com/order/orderlink/deliverydetail/application/dtos/DeliveryDetailService.java
  src/main/java/com/order/orderlink/deliverydetail/domain/repository/DeliveryDetailRepository.java
  src/main/java/com/order/orderlink/deliverydetail/presentation/DeliveryDetailController.java
  src/main/java/com/order/orderlink/user/domain/User.java
Labels: fix

#25 [Feat] 운영지역 crud 기능 추가
  src/main/java/com/order/orderlink/category/application/dtos/CategoryRequest.java
  src/main/java/com/order/orderlink/category/presentation/CategoryController.java
  src/main/java/com/order/orderlink/common/enums/ErrorCode.java
  src/main/java/com/order/orderlink/common/enums/SuccessCode.java
  src/main/java/com/order/orderlink/common/exception/RegionException.java
  src/main/java/com/order/orderlink/order/presentation/OrderController.java
  src/main/java/com/order/orderlink/payment/presentation/PaymentController.java
  src/main/java/com/order/orderlink/region/application/RegionService.java
  src/main/java/com/order/orderlink/region/application/dtos/RegionDTO.java
  src/main/java/com/order/orderlink/region/application/dtos/RegionRequest.java
  src/main/java/com/order/orderlink/region/application/dtos/RegionResponse.java
  src/main/java/com/order/orderlink/region/domain/Region.java
  src/main/java/com/order/orderlink/region/domain/repository/JpaRegionRepository.java
  src/main/java/com/order/orderlink/region/presentation/RegionController.java
Labels: feat

#24 [Feat] 음식 삭제 기능 추가
  src/main/java/com/order/orderlink/common/enums/SuccessCode.java
  src/main/java/com/order/orderlink/food/application/FoodService.java
  src/main/java/com/order/orderlink/food/application/dtos/FoodResponse.java
  src/main/java/com/order/orderlink/food/domain/Food.java
  src/main/java/com/order/orderlink/food/presentation/FoodController.java
Labels: feat

#26 [Feat] AI를 통해 음식 설명을 추천받는 API 추가
  src/main/java/com/order/orderlink/ai/application/AiApiService.java
  src/main/java/com/order/orderlink/ai/application/dtos/AiApiRequest.java
  src/main/java/com/order/orderlink/ai/application/dtos/AiApiResponse.java
  src/main/java/com/order/orderlink/ai/domain/AiApiLog.java
  src/main/java/com/order/orderlink/ai/domain/repository/AiApiLogRepository.java
  src/main/java/com/order/orderlink/ai/presentation/AiApiController.java
  src/main/java/com/order/orderlink/common/config/AiWebClientConfig.java
  src/main/java/com/order/orderlink/common/enums/ErrorCode.java
  src/main/java/com/order/orderlink/common/enums/SuccessCode.java
  src/main/java/com/order/orderlink/common/exception/AiApiException.java
  src/main/resources/application.properties
Labels: feat

#27 [Chore] 세미콜론 정리
  src/main/java/com/order/orderlink/common/enums/ErrorCode.java
  src/main/java/com/order/orderlink/common/enums/SuccessCode.java
Labels: chore

#22 [Feat] 음식점 등록, 전체 음식점 조회 API 추가
  src/main/java/com/order/orderlink/common/auth/util/LocalTimeToStringConverter.java
  src/main/java/com/order/orderlink/common/config/SecurityConfig.java
  src/main/java/com/order/orderlink/common/enums/SuccessCode.java
  src/main/java/com/order/orderlink/restaurant/application/RestaurantService.java
  src/main/java/com/order/orderlink/restaurant/application/dtos/RestaurantRequest.java
  src/main/java/com/order/orderlink/restaurant/application/dtos/RestaurantResponse.java
  src/main/java/com/order/orderlink/restaurant/domain/Restaurant.java
  src/main/java/com/order/orderlink/restaurant/presentation/RestaurantController.java
Labels: feat

#28 [Feat] s3 설정 및 음식 조회 , 목록 조회 추가 및 food 쪽 api 수정
  build.gradle
  src/main/java/com/order/orderlink/common/config/S3Config.java
  src/main/java/com/order/orderlink/common/config/SecurityConfig.java
  src/main/java/com/order/orderlink/common/enums/SuccessCode.java
  src/main/java/com/order/orderlink/common/external/s3/S3Service.java
  src/main/java/com/order/orderlink/food/application/FoodService.java
  src/main/java/com/order/orderlink/food/application/dtos/FoodDTO.java
  src/main/java/com/order/orderlink/food/application/dtos/FoodRequest.java
  src/main/java/com/order/orderlink/food/application/dtos/FoodResponse.java
  src/main/java/com/order/orderlink/food/domain/Food.java
  src/main/java/com/order/orderlink/food/presentation/FoodController.java
  src/main/resources/application.properties
Labels: feat

#29 [Feat] 리뷰 등록/조회(목록, 상세)/수정/삭제 API 추가
  src/main/java/com/order/orderlink/address/domain/Address.java
  src/main/java/com/order/orderlink/address/presentation/AddressController.java
  src/main/java/com/order/orderlink/ai/domain/AiApiLog.java
  src/main/java/com/order/orderlink/common/config/SecurityConfig.java
  src/main/java/com/order/orderlink/common/enums/ErrorCode.java
  src/main/java/com/order/orderlink/common/enums/SuccessCode.java
  src/main/java/com/order/orderlink/common/exception/ReviewException.java
  src/main/java/com/order/orderlink/restaurant/domain/Restaurant.java
  src/main/java/com/order/orderlink/review/application/ReviewService.java
  src/main/java/com/order/orderlink/review/application/dtos/ReviewRequest.java
  src/main/java/com/order/orderlink/review/application/dtos/ReviewResponse.java
  src/main/java/com/order/orderlink/review/domain/Review.java
  src/main/java/com/order/orderlink/review/domain/repository/ReviewRepository.java
  src/main/java/com/order/orderlink/review/presentation/ReviewController.java
  src/main/java/com/order/orderlink/user/presentation/UserController.java
Labels: feat

#30 [Refactor] restaurantClient 추가
  src/main/java/com/order/orderlink/common/client/RestaurantClient.java
  src/main/java/com/order/orderlink/common/enums/ErrorCode.java
  src/main/java/com/order/orderlink/food/application/FoodService.java
  src/main/java/com/order/orderlink/order/application/OrderService.java
  src/main/java/com/order/orderlink/payment/application/dtos/PaymentRequest.java
  src/main/java/com/order/orderlink/restaurant/application/RestaurantService.java
  src/main/java/com/order/orderlink/restaurant/domain/Restaurant.java
  src/main/java/com/order/orderlink/restaurant/presentation/RestaurantController.java
  src/main/java/com/order/orderlink/user/application/UserService.java
  src/main/java/com/order/orderlink/user/domain/User.java
Labels: refactor

#32 [Test] 주문 검색 테스트 코드 작성
  build.gradle
  src/main/java/com/order/orderlink/order/domain/repository/OrderRepositoryImpl.java
  src/test/java/com/order/orderlink/order/OrderRepositoryTest.java
  src/test/resources/application-test.properties
Labels: test

#33 [Test] 운영지역, 결제 내역, 카테고리 테스트 추가
  src/main/java/com/order/orderlink/category/application/CategoryService.java
  src/main/java/com/order/orderlink/category/application/dtos/CategoryRequest.java
  src/main/java/com/order/orderlink/category/domain/repository/CategoryRepository.java
  src/main/java/com/order/orderlink/category/domain/repository/RestaurantCategoryRepository.java
  src/main/java/com/order/orderlink/payment/application/PaymentService.java
  src/main/java/com/order/orderlink/payment/application/dtos/PaymentRequest.java
  src/main/java/com/order/orderlink/payment/domain/repository/PaymentRepository.java
  src/main/java/com/order/orderlink/region/application/RegionService.java
  src/main/java/com/order/orderlink/region/application/dtos/RegionRequest.java
  src/main/java/com/order/orderlink/region/domain/repository/RegionRepository.java
  src/test/java/com/order/orderlink/category/application/CategoryServiceTest.java
  src/test/java/com/order/orderlink/order/domain/OrderRepositoryTest.java
  src/test/java/com/order/orderlink/payment/application/PaymentServiceTest.java
  src/test/java/com/order/orderlink/region/application/RegionServiceTest.java
Labels: test

#31 [Feat] 음식점 정보 수정, 음식점 삭제 API 추가
  src/main/java/com/order/orderlink/common/config/SecurityConfig.java
  src/main/java/com/order/orderlink/common/enums/ErrorCode.java
  src/main/java/com/order/orderlink/common/enums/SuccessCode.java
  src/main/java/com/order/orderlink/restaurant/application/RestaurantService.java
  src/main/java/com/order/orderlink/restaurant/application/TokenGenerator.java
  src/main/java/com/order/orderlink/restaurant/application/dtos/RestaurantRequest.java
  src/main/java/com/order/orderlink/restaurant/application/dtos/RestaurantResponse.java
  src/main/java/com/order/orderlink/restaurant/domain/Restaurant.java
  src/main/java/com/order/orderlink/restaurant/presentation/RestaurantController.java
Labels: feat

#34 [Refactor] 보안되지 않은 API에서 보안되어 있는 API 호출이 가능하도록 인가 관련 로직 추가
  src/main/java/com/order/orderlink/common/auth/ServiceAccountUserDetails.java
  src/main/java/com/order/orderlink/common/auth/controller/ServiceAccountTokenController.java
  src/main/java/com/order/orderlink/common/auth/filter/JwtAuthorizationFilter.java
  src/main/java/com/order/orderlink/common/auth/service/ServiceAccountTokenService.java
  src/main/java/com/order/orderlink/common/client/OrderClient.java
  src/main/java/com/order/orderlink/common/client/UserClient.java
  src/main/java/com/order/orderlink/common/config/SecurityConfig.java
  src/main/java/com/order/orderlink/common/enums/ErrorCode.java
  src/main/java/com/order/orderlink/review/application/ReviewService.java
  src/main/resources/application.properties
Labels: refactor

#35 [Feat] 특정 카테고리가 적용된 음식점 목록 조회 API 기능 구현
  src/main/java/com/order/orderlink/category/application/CategoryService.java
  src/main/java/com/order/orderlink/category/domain/Category.java
  src/main/java/com/order/orderlink/category/domain/RestaurantCategory.java
  src/main/java/com/order/orderlink/category/domain/repository/RestaurantCategoryRepository.java
  src/main/java/com/order/orderlink/common/enums/SuccessCode.java
  src/main/java/com/order/orderlink/restaurant/application/RestaurantService.java
  src/main/java/com/order/orderlink/restaurant/application/dtos/RestaurantRequest.java
  src/main/java/com/order/orderlink/restaurant/application/dtos/RestaurantResponse.java
  src/main/java/com/order/orderlink/restaurant/domain/Restaurant.java
  src/main/java/com/order/orderlink/restaurant/domain/repository/RestaurantRepository.java
  src/main/java/com/order/orderlink/restaurant/presentation/RestaurantController.java
Labels: feat

#36 [Refactor] 음식점 카테고리 등록 수정
  src/main/java/com/order/orderlink/category/application/CategoryService.java
  src/main/java/com/order/orderlink/category/domain/RestaurantCategory.java
  src/main/java/com/order/orderlink/category/domain/repository/RestaurantCategoryRepository.java
  src/main/java/com/order/orderlink/common/config/SecurityConfig.java
  src/main/java/com/order/orderlink/food/application/FoodService.java
  src/main/java/com/order/orderlink/food/domain/repository/FoodRepository.java
  src/main/java/com/order/orderlink/food/presentation/FoodController.java
  src/main/java/com/order/orderlink/restaurant/application/RestaurantService.java
  src/main/java/com/order/orderlink/restaurant/application/dtos/RestaurantResponse.java
  src/main/java/com/order/orderlink/restaurant/domain/Restaurant.java
  src/main/java/com/order/orderlink/restaurant/presentation/RestaurantController.java
  src/test/java/com/order/orderlink/category/application/CategoryServiceTest.java
  src/test/java/com/order/orderlink/order/domain/OrderRepositoryTest.java
  src/test/resources/application-test.properties
Labels: refactor

#37 [Test] User 단위테스트 추가
  src/main/java/com/order/orderlink/user/application/dtos/UserRequest.java
  src/test/java/com/order/orderlink/user/application/UserServiceTest.java
Labels: test
